"""
bench.py — compares WITH vs WITHOUT the pipeline. REAL numbers, nothing made up.

Each case = {goal, target, criteria, test_cmd}.
  WITHOUT: sends only the raw goal to the LLM (baseline).
  WITH:    full pipeline (precedent + skill + layers + verify).
Measures: did it pass the test on the first try? how many attempts?

Usage: simplicio-py bench --cases bench/cases.json --stack angular
Writes bench/results.md with the real table.
"""

import json
import os
import subprocess
import time
from pathlib import Path

from .observability import estimate_tokens, log_run
from .prompt import build_prompt
from .providers import generate
from .runtime_env import wrap_project_command


def _test(output: str, root: str, test_cmd: str) -> bool:
    os.makedirs(os.path.join(root, ".simplicio-loop"), exist_ok=True)
    Path(root, ".simplicio-loop", "bench_out.txt").write_text(output or "", encoding="utf-8")
    test_cmd = wrap_project_command(root, test_cmd)
    p = subprocess.run(
        test_cmd,
        shell=True,
        cwd=root,
        stdin=subprocess.DEVNULL,
        capture_output=True,
        text=True,
    )
    return p.returncode == 0


def _baseline(case: dict[str, str], root: str) -> str:
    # baseline: raw goal, zero built context
    prompt = case["goal"]
    out = generate(prompt)
    log_run(
        root,
        {
            "mode": "baseline",
            "goal": case["goal"],
            "target": case.get("target", ""),
            "tokens_estimated": estimate_tokens(prompt) + estimate_tokens(out),
        },
    )
    return out


def _pipeline(case: dict[str, str], root: str, stack: str) -> str:
    prompt = build_prompt(
        root,
        stack,
        case["goal"],
        case["target"],
        case.get("criteria", "- true state\n- false state"),
        case.get("constraints", "- build passes"),
    )
    out = generate(prompt)
    log_run(
        root,
        {
            "mode": "pipeline",
            "goal": case["goal"],
            "target": case.get("target", ""),
            "tokens_estimated": estimate_tokens(prompt) + estimate_tokens(out),
        },
    )
    return out


def run_bench(root: str, stack: str, cases_path: str) -> int:
    try:
        cases = json.loads(Path(cases_path).read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        print(f"simplicio-py: error: cannot read benchmark cases: {exc}")
        return 1
    if not isinstance(cases, list):
        print("simplicio-py: error: benchmark cases must be a JSON list")
        return 1
    rows, n = [], len(cases)
    if n == 0:
        print("simplicio-py: error: benchmark cases list is empty")
        return 1
    hits = {"without": 0, "with": 0}
    hallucination_flags = {"without": 0, "with": 0}
    for c in cases:
        tc = c["test_cmd"]
        out_without = _baseline(c, root)
        ok_without = _test(out_without, root, tc)
        hits["without"] += ok_without
        out_with = _pipeline(c, root, stack)
        ok_with = _test(out_with, root, tc)
        hits["with"] += ok_with
        target = c.get("target", "")
        hallucination_flags["without"] += int(bool(target and out_without and target not in out_without))
        hallucination_flags["with"] += int(bool(target and out_with and target not in out_with))
        rows.append(
            f"| {c['goal'][:40]} | {'PASS' if ok_without else 'FAIL'} | {'PASS' if ok_with else 'FAIL'} |"
        )
    table = (
        "| Task | Without simplicio | With simplicio |\n|---|---|---|\n"
        + "\n".join(rows)
        + f"\n\n**First-try pass rate:** without = {hits['without']}/{n} "
        f"({100 * hits['without'] // n}%) · with = {hits['with']}/{n} "
        f"({100 * hits['with'] // n}%)"
        + f"\n\n**Hallucinated-target flags:** without = {hallucination_flags['without']}/{n} "
        f"· with = {hallucination_flags['with']}/{n}"
    )
    out = os.path.join(root, "bench", "results.md")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    Path(out).write_text(
        f"# Benchmark (generated by `simplicio-py bench`)\n\n"
        f"Provider: {os.environ.get('SIMPLICIO_PROVIDER', 'claude')} · "
        f"cases: {n} · date: {time.strftime('%Y-%m-%d')}\n\n{table}\n",
        encoding="utf-8",
    )
    print(table)
    print(f"\n-> {out}")
    return 0
