"""Plan compiler contracts (issue #166): Goal + Mapper context -> PlanDAG.

Public surface only — see :mod:`simplicio.plan_compiler.models` for the
schema definitions and ``docs/plan-compiler.md`` for the contract writeup.
"""

from __future__ import annotations

from simplicio.plan_compiler.authority import (
    AUTHORIZATION_SCHEMA,
    PROPOSAL_SCHEMA,
    AuthorizationError,
    ChangeProposal,
    EffectAuthorization,
    build_change_proposal,
)
from simplicio.plan_compiler.canonical_hash import canonical_hash
from simplicio.plan_compiler.compat_adapter import (
    GOAL_ENVELOPE_ADAPTER_EXPIRES_AT_VERSION,
    GOAL_ENVELOPE_VERSION,
    PLAN_DAG_ADAPTER_EXPIRES_AT_VERSION,
    PLAN_DAG_VERSION,
    CompatAdapterError,
    CompatAdapterExpiredError,
    UnsupportedCompatVersionError,
    adapt_goal_envelope_inbound,
    adapt_goal_envelope_outbound,
    adapt_inbound,
    adapt_outbound,
)
from simplicio.plan_compiler.compile_task_spec import (
    PlanCompilationError,
    compile_task_spec_to_plan,
)
from simplicio.plan_compiler.conformance import (
    PLAN_CONTRACT_CONSUMERS,
    PLAN_CONTRACT_OWNER,
    PLAN_PROJECTION_SCHEMA,
    PlanProjection,
    create_plan_projection,
    plan_contract_manifest,
    validate_plan_projection,
)
from simplicio.plan_compiler.effect_sink import (
    EffectDispatchContext,
    EffectOutcome,
    EffectSink,
    IntegratedModeRequiresSinkError,
    RecordingEffectSink,
)
from simplicio.plan_compiler.errors import (
    PlanCompilerError,
    PlanValidationError,
    SchemaMismatchError,
)
from simplicio.plan_compiler.execution_contracts import (
    BOUND_VERIFICATION_PLAN_SCHEMA,
    CHANGE_SET_SCHEMA,
    BoundVerificationPlan,
    ChangeOperation,
    ChangeSet,
    ContextHashes,
    VerificationCommand,
)
from simplicio.plan_compiler.mapper_context import (
    DEV_CLI_CONTEXT_HANDLE_SCHEMA,
    DEV_CLI_FALLBACK_CONTEXT_SCHEMA,
    MAPPER_CONTEXT_PACK_SCHEMA,
    MAPPER_CONTEXT_SNAPSHOT_SCHEMA,
    MAPPER_CONTRACT_COMMIT,
    MAPPER_CONTRACT_MANIFEST_SHA256,
    MAPPER_EXECUTION_CONTEXT_SCHEMA,
    ContextBinding,
    ContextBindingCache,
    ContextHandle,
    MapperContextAdapter,
    MapperContextError,
    MapperContextPackAdapter,
    MapperContextView,
    bind_mapper_context,
    load_mapper_context,
    load_mapper_context_pack,
    load_mapper_execution_context,
    verify_context_sources,
)
from simplicio.plan_compiler.models import (
    EFFECT_PLAN_SCHEMA,
    GOAL_ENVELOPE_SCHEMA,
    PLAN_COMPILER_COMPATIBILITY,
    PLAN_DAG_SCHEMA,
    VERIFICATION_PLAN_SCHEMA,
    EffectPlan,
    GoalEnvelope,
    PlanDAG,
    PlanNode,
    VerificationPlan,
)
from simplicio.plan_compiler.runtime_effect_sink import (
    OfflineRuntimeTransport,
    RuntimeEffectError,
    RuntimeEffectSink,
)

__all__ = [
    "ContextBinding",
    "ContextHashes",
    "ContextBindingCache",
    "AUTHORIZATION_SCHEMA",
    "AuthorizationError",
    "ContextHandle",
    "DEV_CLI_CONTEXT_HANDLE_SCHEMA",
    "DEV_CLI_FALLBACK_CONTEXT_SCHEMA",
    "EFFECT_PLAN_SCHEMA",
    "CHANGE_SET_SCHEMA",
    "BOUND_VERIFICATION_PLAN_SCHEMA",
    "GOAL_ENVELOPE_ADAPTER_EXPIRES_AT_VERSION",
    "GOAL_ENVELOPE_SCHEMA",
    "GOAL_ENVELOPE_VERSION",
    "PLAN_COMPILER_COMPATIBILITY",
    "PLAN_CONTRACT_CONSUMERS",
    "PLAN_CONTRACT_OWNER",
    "PLAN_DAG_ADAPTER_EXPIRES_AT_VERSION",
    "PLAN_DAG_SCHEMA",
    "PLAN_DAG_VERSION",
    "PLAN_PROJECTION_SCHEMA",
    "VERIFICATION_PLAN_SCHEMA",
    "CompatAdapterError",
    "CompatAdapterExpiredError",
    "EffectDispatchContext",
    "EffectAuthorization",
    "EffectOutcome",
    "EffectPlan",
    "EffectSink",
    "ChangeOperation",
    "ChangeSet",
    "BoundVerificationPlan",
    "OfflineRuntimeTransport",
    "GoalEnvelope",
    "IntegratedModeRequiresSinkError",
    "MAPPER_CONTRACT_COMMIT",
    "MAPPER_CONTRACT_MANIFEST_SHA256",
    "MAPPER_CONTEXT_PACK_SCHEMA",
    "MAPPER_CONTEXT_SNAPSHOT_SCHEMA",
    "MAPPER_EXECUTION_CONTEXT_SCHEMA",
    "MapperContextAdapter",
    "MapperContextError",
    "MapperContextPackAdapter",
    "MapperContextView",
    "PlanCompilationError",
    "PlanCompilerError",
    "PlanDAG",
    "PlanNode",
    "PlanProjection",
    "PlanValidationError",
    "RecordingEffectSink",
    "PROPOSAL_SCHEMA",
    "RuntimeEffectError",
    "ChangeProposal",
    "build_change_proposal",
    "RuntimeEffectSink",
    "SchemaMismatchError",
    "UnsupportedCompatVersionError",
    "VerificationPlan",
    "VerificationCommand",
    "adapt_goal_envelope_inbound",
    "adapt_goal_envelope_outbound",
    "adapt_inbound",
    "adapt_outbound",
    "bind_mapper_context",
    "canonical_hash",
    "compile_task_spec_to_plan",
    "create_plan_projection",
    "load_mapper_context",
    "plan_contract_manifest",
    "validate_plan_projection",
    "load_mapper_context_pack",
    "load_mapper_execution_context",
    "verify_context_sources",
]
