"""Public MapperStore/v1 Python foundation.

This package owns connection policy and lifecycle only. Domain schemas belong to
later MapperStore issues; importing it performs no filesystem or SQLite work.
"""

from .catalog import (
    CATALOG_API_SCHEMA,
    CATALOG_MANIFEST_NAME,
    ECOSYSTEM_BANKS,
    absorb_all,
    absorb_bank,
    bank_by_id,
    data_status,
    ensure_mapper_memory,
    layout_tree,
)
from .connection import (
    StoreConnection,
    StoreError,
    StoreIntegrityError,
    StoreMissingError,
    WriterIdentity,
)
from .health import (
    CAPACITY_SCHEMA,
    DOCTOR_SCHEMA,
    HEALTH_STATES,
    REPAIR_SCHEMA,
    DoctorError,
    backup_store,
    capacity_report,
    doctor_store,
    redact,
    repair_store,
    restore_store,
    secure_export,
)
from .locks import StoreFileLock, StoreLockError
from .memory import (
    MEMORY_API_SCHEMA,
    MEMORY_HANDOFF_SCHEMA,
    MEMORY_SCHEMA,
    MEMORY_SNAPSHOT_SCHEMA,
    MEMORY_VALIDATION_SCHEMA,
    MarkdownGitAdapter,
    MemoryStore,
    MemoryStoreError,
    build_handoff,
    init_memory,
    memory_dir,
    recall_memory,
    store_memory,
    validate_memory,
)
from .migration import (
    MIGRATION_API_SCHEMA,
    MIGRATION_DISCOVERY_SCHEMA,
    MIGRATION_PLAN_SCHEMA,
    MIGRATION_SCHEMA,
    MIGRATION_STATUS_SCHEMA,
    STATES,
    MigrationCoordinator,
    MigrationCoordinatorError,
)
from .neural import (
    NEURAL_API_SCHEMA,
    NEURAL_DB_NAME,
    NeuralBankError,
    absorb_runtime_neural,
    apply_migrations,
    bootstrap_neural,
    neural_database_path,
    neural_status,
    seed_neural,
)
from .observability import BENCHMARK_SCHEMA, METRICS_SCHEMA, Metrics, metrics_for_store, run_benchmark
from .operations import OPERATIONS_API_SCHEMA, OPERATIONS_SCHEMA, OperationsStore, OperationsStoreError
from .paths import StoreLocation, StorePathError, assert_within_root, resolve_store_location
from .profiles import StoreMode, StoreProfile
from .project_scope import (
    ScopedDataLayout,
    core_data_root,
    project_data_root,
    resolve_project_slug,
    resolve_scoped_layout,
    sanitize_project_slug,
)
from .registry import (
    DEFAULT_MANIFEST,
    MIGRATION_EVENT_SCHEMA,
    SCHEMA_REGISTRY,
    AmbiguousMigrationError,
    IncompatibleWriterError,
    MigrationEngine,
    MigrationFault,
    MigrationPreflightError,
    MigrationSpec,
    RegistryChecksumError,
    RegistryError,
    canonical_json,
    default_migrations,
    negotiate,
    registry_fixture,
    sha256_json,
)
from .semantic import (
    BITEMPORAL_RELATION_SCHEMA,
    SEMANTIC_API_SCHEMA,
    SEMANTIC_SCHEMA,
    SemanticStore,
    SemanticStoreError,
)
from .status import inspect_store
from .transactions import (
    FenceValidator,
    FenceViolationError,
    TransactionError,
    is_busy_error,
    run_with_retry,
    transaction,
)
from .unify import (
    CANONICAL_DB_NAME,
    UNIFY_API_SCHEMA,
    canonical_memory_path,
    unify_memory,
    unify_status,
)
from .unify import (
    env_hints as memory_env_hints,
)


def __getattr__(name: str):
    """Load the canonical facade lazily to keep the legacy export graph stable."""
    if name in {"MapperStore", "MapperStoreError", "MapperStoreReader"}:
        from .canonical import MapperStore, MapperStoreError, MapperStoreReader

        return {"MapperStore": MapperStore, "MapperStoreError": MapperStoreError, "MapperStoreReader": MapperStoreReader}[name]
    if name.startswith("MAPPER_STORE_"):
        from . import contracts

        return getattr(contracts, name)
    raise AttributeError(name)

__all__ = [
    "MapperStore",
    "MapperStoreError",
    "MapperStoreReader",
    "MAPPER_STORE_ABSORB_SCHEMA",
    "MAPPER_STORE_API_SCHEMA",
    "MAPPER_STORE_CAPABILITY_SCHEMA",
    "MAPPER_STORE_CONFORMANCE_SCHEMA",
    "MAPPER_STORE_READERS",
    "MAPPER_STORE_RECORD_SCHEMA",
    "MAPPER_STORE_SCHEMA",
    "MAPPER_STORE_WRITER",
    "FenceValidator",
    "FenceViolationError",
    "StoreConnection",
    "StoreError",
    "StoreFileLock",
    "StoreIntegrityError",
    "StoreLocation",
    "StoreLockError",
    "StoreMissingError",
    "CAPACITY_SCHEMA",
    "DOCTOR_SCHEMA",
    "REPAIR_SCHEMA",
    "DoctorError",
    "HEALTH_STATES",
    "backup_store",
    "capacity_report",
    "doctor_store",
    "redact",
    "repair_store",
    "restore_store",
    "secure_export",
    "BENCHMARK_SCHEMA",
    "METRICS_SCHEMA",
    "Metrics",
    "metrics_for_store",
    "run_benchmark",
    "MIGRATION_API_SCHEMA",
    "MIGRATION_DISCOVERY_SCHEMA",
    "MIGRATION_PLAN_SCHEMA",
    "MIGRATION_SCHEMA",
    "MIGRATION_STATUS_SCHEMA",
    "MigrationCoordinator",
    "MigrationCoordinatorError",
    "STATES",
    "MEMORY_API_SCHEMA",
    "MEMORY_HANDOFF_SCHEMA",
    "MEMORY_SCHEMA",
    "MEMORY_SNAPSHOT_SCHEMA",
    "MEMORY_VALIDATION_SCHEMA",
    "MarkdownGitAdapter",
    "MemoryStore",
    "MemoryStoreError",
    "StoreMode",
    "StorePathError",
    "StoreProfile",
    "AmbiguousMigrationError",
    "DEFAULT_MANIFEST",
    "IncompatibleWriterError",
    "MIGRATION_EVENT_SCHEMA",
    "MigrationEngine",
    "MigrationFault",
    "MigrationPreflightError",
    "MigrationSpec",
    "RegistryChecksumError",
    "RegistryError",
    "SCHEMA_REGISTRY",
    "SEMANTIC_API_SCHEMA",
    "SEMANTIC_SCHEMA",
    "SemanticStore",
    "SemanticStoreError",
    "BITEMPORAL_RELATION_SCHEMA",
    "OPERATIONS_API_SCHEMA",
    "OPERATIONS_SCHEMA",
    "OperationsStore",
    "OperationsStoreError",
    "TransactionError",
    "WriterIdentity",
    "assert_within_root",
    "canonical_json",
    "default_migrations",
    "inspect_store",
    "build_handoff",
    "init_memory",
    "memory_dir",
    "recall_memory",
    "is_busy_error",
    "negotiate",
    "registry_fixture",
    "resolve_store_location",
    "run_with_retry",
    "sha256_json",
    "store_memory",
    "transaction",
    "validate_memory",
    "NEURAL_API_SCHEMA",
    "NEURAL_DB_NAME",
    "NeuralBankError",
    "absorb_runtime_neural",
    "apply_migrations",
    "bootstrap_neural",
    "neural_database_path",
    "neural_status",
    "seed_neural",
    "CATALOG_API_SCHEMA",
    "CATALOG_MANIFEST_NAME",
    "ECOSYSTEM_BANKS",
    "absorb_all",
    "absorb_bank",
    "bank_by_id",
    "data_status",
    "ensure_mapper_memory",
    "layout_tree",
    "CANONICAL_DB_NAME",
    "UNIFY_API_SCHEMA",
    "canonical_memory_path",
    "memory_env_hints",
    "unify_memory",
    "unify_status",
    "ScopedDataLayout",
    "core_data_root",
    "project_data_root",
    "resolve_project_slug",
    "resolve_scoped_layout",
    "sanitize_project_slug",
]
