"""Interfaces first: one contract stub per dependency edge between squads (#1504, part of #1502).

The general coordinator calls ``contracts_for`` + ``write_contracts`` BEFORE the squads start.
The consumer squad codes against the stub's signature; the producer squad replaces the body.
The generated contract test checks the signature and is ``xfail`` until the body is implemented.

Edge: ``{"producer": squad, "consumer": squad, "signature": optional "def f(...) -> ..."}`` or a
``(producer, consumer)`` pair.
"""

from __future__ import annotations

import ast
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Mapping

# Where contracts live in the TARGET repo. Not a shipped package: the stub and its test sit side by side
# and the test loads the stub by file path, so no package or sys.path setup is needed.
DEFAULT_DEST = ".simplicio-loop/contracts"

_TEST_TEMPLATE = '''"""Contract {producer} -> {consumer}: generated by the general coordinator, do not weaken."""

import importlib.util
import inspect
from pathlib import Path

import pytest

MODULE_FILE = Path(__file__).with_name("{stub_name}")
FUNCTION = "{function}"
PARAMS = {params!r}


def _fn():
    spec = importlib.util.spec_from_file_location("{base}", MODULE_FILE)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return getattr(mod, FUNCTION)


def test_contract_signature():
    assert list(inspect.signature(_fn()).parameters) == PARAMS


@pytest.mark.xfail(raises=NotImplementedError, strict=False, reason="contract: {producer} not implemented yet")
def test_contract_implemented():
    _fn()({call_args})
'''

_STUB_TEMPLATE = '''"""Contract stub {producer} -> {consumer}. Producer squad: replace the body, keep the signature."""


{signature}:
    raise NotImplementedError("contract: {producer}")
'''


@dataclass(frozen=True)
class Contract:
    producer: str
    consumer: str
    module_path: str
    test_path: str
    signature: str
    function: str
    test_template: str


def _ident(name: str) -> str:
    return re.sub(r"\W+", "_", str(name).strip()).strip("_").lower() or "squad"


def _edge(edge: Any) -> tuple[str, str, str | None]:
    if isinstance(edge, Mapping):
        return str(edge["producer"]), str(edge["consumer"]), edge.get("signature")
    producer, consumer = edge
    return str(producer), str(consumer), None


def contracts_for(edges: Iterable[Any], dest: str = DEFAULT_DEST) -> list[Contract]:
    """``dest``: directory, relative to the target repo, that holds each stub and its contract test."""
    dest = str(dest).strip().strip("/")
    if not dest or ".." in dest.split("/"):
        raise ValueError(f"dest must be a relative path inside the repo: {dest!r}")
    out: list[Contract] = []
    seen: set[tuple[str, str]] = set()
    for edge in edges:
        producer, consumer, signature = _edge(edge)
        if (producer, consumer) in seen:
            continue
        seen.add((producer, consumer))
        base = f"{_ident(producer)}_to_{_ident(consumer)}"
        signature = signature or f"def {base}(payload: dict) -> dict"
        fn = ast.parse(signature + ":\n    pass").body[0]
        if not isinstance(fn, ast.FunctionDef):
            raise ValueError(f"signature is not a function definition: {signature!r}")
        params = [a.arg for a in fn.args.args]
        module = f"{dest}/{base}.py"
        template = _TEST_TEMPLATE.format(
            producer=producer, consumer=consumer, stub_name=f"{base}.py", base=base,
            function=fn.name, params=params, call_args=", ".join("None" for _ in params),
        )
        out.append(Contract(producer, consumer, module, f"{dest}/test_{base}.py", signature, fn.name, template))
    return out


def _create(repo: Path, rel: str, content: str, res: dict[str, list[str]]) -> None:
    path = repo / rel
    if path.exists():
        res["skipped"].append(rel)
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    res["written"].append(rel)


def write_contracts(repo: str | Path, contracts: Iterable[Contract]) -> dict[str, list[str]]:
    """Create stubs and contract tests; existing files are never overwritten (listed under ``skipped``)."""
    root = Path(repo)
    res: dict[str, list[str]] = {"written": [], "skipped": []}
    contracts = list(contracts)
    for c in contracts:
        _create(root, c.module_path, _STUB_TEMPLATE.format(producer=c.producer, consumer=c.consumer, signature=c.signature), res)
        _create(root, c.test_path, c.test_template, res)
    return res
