#!/usr/bin/env python3
"""Drift gate for `simplicio.dashboard-event/v1` (issue #1398), run by `scripts/check.py`.

1. Every fixture line under `contracts/dashboard-event/v1/fixtures/` validates against
   `schema.json` (jsonschema) AND the emitter's stdlib validator, and the two always agree;
   every line of `invalid.jsonl` is rejected by both.
2. The fixtures are regenerated by the REAL producers (the runner's `_transition`/`_emit_event`
   and `technical_debt.record_notice`, the hooks' emission helpers, the retroactive adapter) in a
   temporary repo and compared with the committed ones after normalizing the per-run volatile
   fields (`event_id`, `ts`, `producer_version`). Any difference is drift.
3. The kind catalog agrees across `schema.json`, the emitter and `docs/DASHBOARD_EVENTS.md`.

Usage:
    python3 scripts/check_dashboard_event_contract.py            # check (exit 0 ok, 1 drift)
    python3 scripts/check_dashboard_event_contract.py --write    # regenerate the fixtures
    python3 scripts/check_dashboard_event_contract.py --fixtures DIR
"""
import argparse
import contextlib
import importlib
import json
import os
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
CONTRACT = os.path.join(REPO, "contracts", "dashboard-event", "v1")
SCHEMA_PATH = os.path.join(CONTRACT, "schema.json")
FIXTURES = os.path.join(CONTRACT, "fixtures")
DOC = os.path.join(REPO, "docs", "DASHBOARD_EVENTS.md")
GENERATED = ("runner-lifecycle.jsonl", "hook-events.jsonl", "derived-legacy-run.jsonl", "watcher-lease.jsonl")
INVALID = "invalid.jsonl"
VOLATILE = ("event_id", "ts", "producer_version")

for path in (HERE, os.path.join(REPO, "hooks"), REPO):
    if path not in sys.path:
        sys.path.insert(0, path)

import dashboard_events as de  # noqa: E402


@contextlib.contextmanager
def _env(**values):
    previous = {k: os.environ.get(k) for k in values}
    os.environ.update({k: v for k, v in values.items()})
    try:
        yield
    finally:
        for key, value in previous.items():
            if value is None:
                os.environ.pop(key, None)
            else:
                os.environ[key] = value


@contextlib.contextmanager
def _cwd(path):
    previous = os.getcwd()
    os.chdir(path)
    try:
        yield
    finally:
        os.chdir(previous)


def _write_json(path, payload):
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=2)


def _state(run_id):
    return {"schema": "simplicio.run-state/v1", "run_id": run_id, "phase": "intake",
            "task_ids": ["T1"], "ac_ids": ["AC-1"], "events": [], "history": [], "blockers": []}


def generate_runner(root):
    """The runner's real seams: arm transition, named events, transitions, technical debt."""
    from simplicio_loop import runner, technical_debt
    from simplicio_loop import dashboard_events as package_events

    run_id = "run-fixture-lifecycle"
    run_dir = os.path.join(root, ".simplicio-loop", "loop-runs", run_id)
    os.makedirs(run_dir)
    state = _state(run_id)
    _write_json(os.path.join(run_dir, "state.json"), state)
    from pathlib import Path
    rd = Path(run_dir)
    armed = {"ts": "2026-10-02T12:00:00Z", "from": None, "to": "intake",
             "reason": "run armed from raw task", "receipt": str(rd / "task-contract.json")}
    package_events.emit_transition(rd, armed, run_id=run_id)
    runner._emit_event(rd, state, "contract_frozen", receipt=str(rd / "task-contract.json"),
                       message="task contract compiled and frozen")
    runner._emit_event(rd, state, "watcher_challenge", receipt=str(rd / "loop" / "watcher_challenge.json"),
                       message="watcher challenge created")
    runner._transition(rd, state, "mapping", "stack and storage routes frozen; mapper required",
                       receipt=str(rd / "stack-lock.json"))
    runner._emit_event(rd, state, "mapper_fresh", receipt=str(rd / "mapper-context.json"),
                       message="mapper scan, inspect, and handoff are fresh")
    runner._transition(rd, state, "planning", "mapper scan/inspect/handoff persisted",
                       receipt=str(rd / "mapper-context.json"))
    runner._emit_event(rd, state, "plan_ready", receipt=str(rd / "plan.json"),
                       message="validated plan materialized")
    runner._transition(rd, state, "awaiting_decision", "plan derived from task contract + mapper",
                       receipt=str(rd / "plan.json"))
    runner._transition(rd, state, "executing", "operator decision recorded")
    runner._emit_event(rd, state, "worker_claimed", receipt=str(rd / "task-contract.json"),
                       task_id="T1", ac_ids=["AC-1"], message="operator worker claimed task",
                       branch="feat/fixture")
    runner._emit_event(rd, state, "operator_receipt", receipt=str(rd / "operator-receipt.json"),
                       message="operator execution receipt persisted")
    runner._emit_event(rd, state, "test_gate", receipt=str(rd / "evidence-receipt.json"),
                       blocker="", message="test and evidence gate evaluated", status="VERIFIED")
    technical_debt.record_notice(rd, run_id=run_id, reason_code="worktree_isolation_unavailable",
                                 stage="executing", source="runner", message="serial lane used",
                                 next_action="enable git worktrees", work_item_id="T1")
    runner._transition(rd, state, "validating", "operator receipt persisted",
                       receipt=str(rd / "operator-receipt.json"))
    runner._transition(rd, state, "delivering", "watcher passed")
    runner._emit_event(rd, state, "delivery_reconciled", receipt=str(rd / "delivery-receipt.json"),
                       blocker="", message="delivery state reconciled", current_state="pr_open")
    runner._emit_event(rd, state, "oracle_verdict", receipt=str(rd / "completion-receipt.json"),
                       blocker="", message="COMPLETE", verdict="COMPLETE")
    runner._transition(rd, state, "done", "delivery state reconciled",
                       receipt=str(rd / "delivery-receipt.json"))
    return de.read_live_events(run_dir)


def generate_hooks(root):
    """The hooks' real emission helpers, resolving the run through SIMPLICIO_RUN_DIR."""
    run_dir = os.path.join(root, ".simplicio-loop", "orchestrator", "runs", "run-fixture-hooks")
    os.makedirs(run_dir)
    with _env(SIMPLICIO_RUN_DIR=run_dir), _cwd(root):
        user_prompt_submit = importlib.import_module("user_prompt_submit")
        loop_stop = importlib.import_module("loop_stop")
        action_gate = importlib.import_module("action_gate")
        user_prompt_submit._dashboard_prompt_event(
            {"prompt": "implement the issue"}, {"decision": "continue", "reason": "prompt_passthrough"})
        loop_stop._DASHBOARD_ITERATION[:] = [3]
        loop_stop._dashboard("gate_evaluated", severity="info",
                             payload={"gate": "watcher", "verdict": "pending", "status": "UNVERIFIED"})
        loop_stop._dashboard("stall_detected", severity="warning",
                             payload={"fingerprint": "abc123", "streak": 3})
        loop_stop._dashboard("iteration_finished", payload={"outcome": "refeed", "has_evidence": True})
        loop_stop._dashboard("iteration_started", iteration=4, payload={"trigger": "refeed"})
        action_gate._dashboard_gate_blocked("force-push blocked")
        loop_stop._DASHBOARD_ITERATION[:] = []
    return de.read_live_events(run_dir)


def generate_derived(root):
    """A pre-#1398 run: transitions + receipts, and an events.jsonl holding only older records."""
    run_dir = os.path.join(root, ".simplicio-loop", "loop-runs", "run-fixture-legacy")
    os.makedirs(run_dir)
    transitions = [
        {"ts": "2026-09-01T10:00:00Z", "from": None, "to": "intake", "reason": "run armed from raw task",
         "receipt": os.path.join(run_dir, "task-contract.json")},
        {"ts": "2026-09-01T10:00:05Z", "from": "intake", "to": "mapping", "reason": "mapper required"},
        {"ts": "2026-09-01T10:01:00Z", "from": "mapping", "to": "planning", "reason": "mapper persisted",
         "receipt": os.path.join(run_dir, "mapper-context.json")},
        {"ts": "2026-09-01T10:02:00Z", "from": "planning", "to": "executing", "reason": "decision recorded"},
        {"ts": "2026-09-01T10:05:00Z", "from": "executing", "to": "blocked", "reason": "evidence unverified",
         "receipt": os.path.join(run_dir, "evidence-receipt.json")},
    ]
    with open(os.path.join(run_dir, "transitions.jsonl"), "w", encoding="utf-8") as fh:
        for entry in transitions:
            fh.write(json.dumps(entry) + "\n")
    _write_json(os.path.join(run_dir, "state.json"),
                {"schema": "simplicio.run-state/v1", "run_id": "run-fixture-legacy", "phase": "blocked"})
    _write_json(os.path.join(run_dir, "task-contract.json"), {"created_at": "2026-09-01T10:00:00Z"})
    _write_json(os.path.join(run_dir, "mapper-context.json"), {"created_at": "2026-09-01T10:00:59Z"})
    _write_json(os.path.join(run_dir, "plan.json"), {"created_at": "2026-09-01T10:01:30Z"})
    _write_json(os.path.join(run_dir, "evidence-receipt.json"),
                {"status": "UNVERIFIED", "checked_at": "2026-09-01T10:04:59Z"})
    with open(os.path.join(run_dir, "events.jsonl"), "w", encoding="utf-8") as fh:
        fh.write(json.dumps({"schema": "simplicio.event-metadata/v1", "kind": "contract_frozen",
                             "run_id": "run-fixture-legacy"}) + "\n")
    return de.read_events(run_dir)


def generate_watcher(root):
    """The watcher's real lease producer: a run opened at intake, two renewals of the lease, then its loss."""
    from pathlib import Path
    from simplicio_loop.watcher247 import events
    run_id = events.open_run(Path(root), "fixture", 7)
    if run_id is None:
        raise RuntimeError("watcher run not opened")
    events.lease_beat("fixture#7", "renewed", beats=1, ttl_s=180)
    events.lease_beat("fixture#7", "renewed", beats=2, ttl_s=180)
    events.lease_beat("fixture#7", "lost", beats=2, ttl_s=180)
    events.close_run(Path(root), run_id, "failed")
    run_dir = os.path.join(root, ".simplicio-loop", "orchestrator", "runs", run_id)
    return [dict(row, run_id="run-fixture-watcher") for row in de.read_live_events(run_dir)]  # the id carries a clock and a random part


def generate_all():
    with tempfile.TemporaryDirectory() as root, \
            _env(SIMPLICIO_LOOP_GITHUB_LIFECYCLE_SYNC="0", SIMPLICIO_DASHBOARD_EVENTS="1",
                 SIMPLICIO_DASHBOARD_EVENTS_DIAGNOSTICS=os.path.join(tempfile.gettempdir(), "dashboard-fixture-diag.jsonl")):
        os.environ.pop("SIMPLICIO_RUN_ID", None)
        return {
            "runner-lifecycle.jsonl": generate_runner(root),
            "hook-events.jsonl": generate_hooks(root),
            "derived-legacy-run.jsonl": generate_derived(root),
            "watcher-lease.jsonl": generate_watcher(root),
        }


def _normalize(evt):
    out = dict(evt)
    for key in VOLATILE:
        if key in out:
            out[key] = "<%s>" % key
    return out


def _read_jsonl(path):
    rows = []
    with open(path, encoding="utf-8") as fh:
        for raw in fh:
            if raw.strip():
                rows.append(json.loads(raw))
    return rows


def _dump_jsonl(path, rows):
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        for row in rows:
            fh.write(json.dumps(row, ensure_ascii=False, sort_keys=False) + "\n")


def check(fixtures):
    errors = []
    try:
        import jsonschema
    except ImportError:
        print("check_dashboard_event_contract: FAIL (jsonschema_unavailable: pip install 'simplicio-loop[dev]')")
        return False
    with open(SCHEMA_PATH, encoding="utf-8") as fh:
        schema = json.load(fh)
    validator = jsonschema.Draft202012Validator(schema)
    for name in GENERATED + (INVALID,):
        path = os.path.join(fixtures, name)
        if not os.path.isfile(path):
            errors.append("%s: fixture missing" % name)
            continue
        for number, row in enumerate(_read_jsonl(path), start=1):
            schema_ok = not list(validator.iter_errors(row))
            stdlib_ok = not de.validate_envelope(row)
            if schema_ok != stdlib_ok:
                errors.append("%s:%d: schema.json and validate_envelope disagree" % (name, number))
            if name == INVALID and (schema_ok or stdlib_ok):
                errors.append("%s:%d: invalid fixture was accepted" % (name, number))
            if name != INVALID and not (schema_ok and stdlib_ok):
                errors.append("%s:%d: %s" % (name, number, "; ".join(de.validate_envelope(row)) or "schema"))
    generated = generate_all()
    for name, rows in generated.items():
        path = os.path.join(fixtures, name)
        if not os.path.isfile(path):
            continue
        committed = [_normalize(r) for r in _read_jsonl(path)]
        fresh = [_normalize(r) for r in rows]
        if committed != fresh:
            errors.append("%s: drift between the committed fixture and the real producer output "
                          "(%d vs %d events); regenerate with --write and review the diff"
                          % (name, len(committed), len(fresh)))
    enum = schema["properties"]["kind"]["anyOf"][0]["enum"]
    if enum != list(de.LOOP_KINDS_ORDERED):
        errors.append("schema.json kind enum != dashboard_events.LOOP_KINDS_ORDERED")
    try:
        with open(DOC, encoding="utf-8") as fh:
            doc = fh.read()
        missing = [k for k in de.LOOP_KINDS_ORDERED if "`%s`" % k not in doc]
        if missing:
            errors.append("docs/DASHBOARD_EVENTS.md does not document kinds: %s" % ", ".join(missing))
    except OSError:
        errors.append("docs/DASHBOARD_EVENTS.md missing")
    for error in errors:
        print("  " + error)
    print("check_dashboard_event_contract: %s" % ("ok" if not errors else "FAIL (%d)" % len(errors)))
    return not errors


def main(argv=None):
    parser = argparse.ArgumentParser(description="dashboard-event/v1 schema + fixture drift gate")
    parser.add_argument("--write", action="store_true", help="regenerate the producer fixtures")
    parser.add_argument("--fixtures", default=FIXTURES, help="fixtures directory to check")
    args = parser.parse_args(argv)
    if args.write:
        os.makedirs(args.fixtures, exist_ok=True)
        for name, rows in generate_all().items():
            _dump_jsonl(os.path.join(args.fixtures, name), rows)
            print("wrote %s (%d events)" % (os.path.join(args.fixtures, name), len(rows)))
        return 0
    return 0 if check(args.fixtures) else 1


if __name__ == "__main__":
    sys.exit(main())
