#!/usr/bin/env python3
"""Self-dogfooding: run simplicio-mapper against this repo, on this repo (issue #165).

simplicio-mapper is sold as "instant project auto-mapping" / the repo-context
base for simplicio-dev-cli and simplicio-loop. This script makes that claim
literal and reproducible rather than an implicit side effect of development:
it runs the real CLI (``simplicio-mapper index . --json``) against THIS
repository, validates the result against the versioned mapper-artifacts
contract (issue #157), and copies a curated, stable snapshot into
``examples/ecosystem-dogfood/`` so visitors have a canonical, browsable
example of what the mapper produces on a real, non-trivial Python+Node
codebase (this one) -- not just a toy fixture.

Scope (see issue #165 and the PR that lands this):

- EXECUTED here: simplicio-mapper's own artifact generation, on this repo,
  via the real CLI entrypoint (not a direct Python function call -- this
  proves the packaged command line actually works end to end).
- DOCUMENTED, NOT EXECUTED here: the cross-repo leg of the full ecosystem
  dogfood recipe (running simplicio-mapper against simplicio-dev-cli and
  simplicio-loop too, a simplicio-dev-cli deterministic-edit example, and a
  simplicio-loop mini-loop run with a journal). That leg needs separate
  checkouts and processes for those other repos, which this single-repo
  script/PR cannot safely orchestrate. See ``examples/ecosystem-dogfood/
  README.md`` -> "Full cross-repo recipe (documented, not executed here)"
  for the exact reproducible steps a maintainer runs by hand across the 3
  repos.

Usage:
  python3 scripts/dogfood.py            # regenerate .simplicio/* + refresh examples/ecosystem-dogfood/
  python3 scripts/dogfood.py --check    # verify examples/ecosystem-dogfood/ is present + contract-valid, no regeneration
  python3 scripts/dogfood.py --help     # this message
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOGFOOD_DIR = os.path.join(ROOT, "examples", "ecosystem-dogfood")
SIMPLICIO_DIR = os.path.join(ROOT, ".simplicio")

# The curated subset copied into examples/ecosystem-dogfood/ -- the three
# artifacts a downstream consumer (simplicio-dev-cli, simplicio-loop, or an
# LLM agent) actually reads per SIMPLICIO_INTEGRATION.md, not the full set
# of internal/cache artifacts this repo keeps in .simplicio/.
CURATED_ARTIFACTS = [
    "project-map.json",
    "precedent-index.json",
    "architecture-inventory.json",
]

README_TEMPLATE = """# Ecosystem dogfooding example

This directory is a **committed, stable snapshot** of what
[`simplicio-mapper`](https://github.com/wesleysimplicio/simplicio-mapper)
produces when it maps **this very repository** -- generated by
[`scripts/dogfood.py`](../../scripts/dogfood.py) (issue #165), which runs
the real, packaged CLI (`simplicio-mapper index . --json`) against the repo
root, exactly the way any downstream consumer would.

Regenerate it with:

```bash
python3 scripts/dogfood.py
```

Verify it (contract-valid, present, no regeneration) with:

```bash
python3 scripts/dogfood.py --check
```

## What's here

| File | Schema | Produced by |
|---|---|---|
| `project-map.json` | `simplicio.project-map/v1` | `simplicio-mapper index . --json` |
| `precedent-index.json` | `simplicio.precedent-index/v1` | `simplicio-mapper index . --json` |
| `architecture-inventory.json` | `simplicio.architecture-inventory/v1` | `simplicio-mapper index . --json` |

These three are the subset a downstream consumer actually reads per
[`SIMPLICIO_INTEGRATION.md`](../../SIMPLICIO_INTEGRATION.md) -- not the
full `.simplicio/` working set (which also carries caches, locks, run
history and rendered docs that are real but not part of the public
contract). All three validate against the versioned schemas in
[`contracts/mapper-artifacts/v1/`](../../contracts/mapper-artifacts/v1/README.md)
(issue #157) -- `scripts/dogfood.py` runs `simplicio-mapper contract
validate` on them before committing the refresh, and fails loudly if any
of them drift from the contract.

`_meta.json` in this directory records when this snapshot was last
regenerated and the mapper version that produced it.

## Full cross-repo recipe (documented, not executed here)

The full ecosystem dogfood story is **mapper + dev-cli + loop across all
three repos**, exercising the real integration contract
(`SIMPLICIO_INTEGRATION.md`): the mapper's artifacts feed
`simplicio-dev-cli`'s deterministic edit precedent lookup, and
`simplicio-loop`'s run-journal ties the whole thing into an autonomous
iteration cycle. That needs three separate checkouts and processes running
together, which a single `simplicio-mapper` PR/session cannot safely
orchestrate (per issue #165's explicit scope cut) -- so it's documented
here as a reproducible recipe for a maintainer to run by hand, not
something this script executes.

1. **Mapper on all three repos** (this repo's own leg is the one this
   script actually runs):

   ```bash
   # in each of simplicio-mapper/, simplicio-dev-cli/, simplicio-loop/
   simplicio-mapper index . --json
   simplicio-mapper contract validate .simplicio/project-map.json \\
     .simplicio/precedent-index.json .simplicio/architecture-inventory.json
   ```

2. **A simplicio-dev-cli deterministic edit example** (in a
   `simplicio-dev-cli` checkout, after step 1 has produced its
   `.simplicio/precedent-index.json`):

   ```bash
   simplicio-dev-cli execute --task "<a small, well-scoped task>" \\
     --context .simplicio/project-map.json --json
   ```

   The dev-cli's 6-layer contract reads the mapper's precedent index to
   ground its edit in real, existing patterns from the repo instead of
   guessing from scratch.

3. **A simplicio-loop mini-loop with a journal** (in a `simplicio-loop`
   checkout, or any repo with the loop installed via
   `bash scripts/install.sh claude`):

   ```bash
   /simplicio-loop "<a small, bounded goal with a measurable acceptance criterion>"
   ```

   The loop's run-journal (`scripts/loop_journal.py`) records each attempt;
   a maintainer can inspect it afterwards to see the mapper's artifacts
   (from step 1) feeding the loop's `orient` step turn over turn.

Each step above is independently reproducible by any contributor with the
three repos checked out side by side -- there is no hidden setup beyond
`pip install simplicio-mapper simplicio-cli` (or the equivalent local
checkouts) and the commands above.
"""


def _run(cmd: list[str], **kwargs) -> subprocess.CompletedProcess:
    print(f"$ {' '.join(cmd)}")
    return subprocess.run(cmd, cwd=ROOT, check=True, **kwargs)


def _read_version() -> str:
    pyproject = os.path.join(ROOT, "pyproject.toml")
    try:
        with open(pyproject, encoding="utf-8") as fh:
            for line in fh:
                if line.strip().startswith("version"):
                    return line.split("=", 1)[1].strip().strip('"')
    except FileNotFoundError:
        return "unknown"
    return "unknown"


def check(argv: argparse.Namespace) -> int:
    """Verify examples/ecosystem-dogfood/ is present and contract-valid, without regenerating."""
    missing = [name for name in CURATED_ARTIFACTS if not os.path.exists(os.path.join(DOGFOOD_DIR, name))]
    if missing:
        print(f"::error::examples/ecosystem-dogfood/ is missing: {missing}. Run `python3 scripts/dogfood.py`.")
        return 1
    meta_path = os.path.join(DOGFOOD_DIR, "_meta.json")
    if not os.path.exists(meta_path):
        print("::error::examples/ecosystem-dogfood/_meta.json is missing.")
        return 1
    paths = [os.path.join(DOGFOOD_DIR, name) for name in CURATED_ARTIFACTS]
    result = _run(
        [sys.executable, "-m", "simplicio_mapper.cli", "contract", "validate", *paths],
        capture_output=True, text=True,
    )
    print(result.stdout)
    print("examples/ecosystem-dogfood/ is present and contract-valid.")
    return 0


def regenerate(argv: argparse.Namespace) -> int:
    """Run the real CLI against this repo, then refresh examples/ecosystem-dogfood/."""
    print(f"Dogfooding simplicio-mapper against its own repo: {ROOT}")
    _run([sys.executable, "-m", "simplicio_mapper.cli", "index", ".", "--json"])

    os.makedirs(DOGFOOD_DIR, exist_ok=True)
    for name in CURATED_ARTIFACTS:
        src = os.path.join(SIMPLICIO_DIR, name)
        if not os.path.exists(src):
            print(f"::error::{src} was not produced by `index` -- aborting refresh.")
            return 1
        shutil.copyfile(src, os.path.join(DOGFOOD_DIR, name))
        print(f"  refreshed examples/ecosystem-dogfood/{name}")

    readme_path = os.path.join(DOGFOOD_DIR, "README.md")
    with open(readme_path, "w", encoding="utf-8") as fh:
        fh.write(README_TEMPLATE)
    print("  refreshed examples/ecosystem-dogfood/README.md")

    meta = {
        "schema": "simplicio.ecosystem-dogfood-meta/v1",
        "generated_by": "scripts/dogfood.py",
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "mapper_version": _read_version(),
        "source_repo": "https://github.com/wesleysimplicio/simplicio-mapper",
        "curated_artifacts": CURATED_ARTIFACTS,
        "note": (
            "Snapshot of `simplicio-mapper index . --json` run against this "
            "repo's own working tree. Cross-repo (dev-cli/loop) legs are "
            "documented, not executed -- see README.md."
        ),
    }
    with open(os.path.join(DOGFOOD_DIR, "_meta.json"), "w", encoding="utf-8") as fh:
        json.dump(meta, fh, indent=2, sort_keys=True)
        fh.write("\n")
    print("  refreshed examples/ecosystem-dogfood/_meta.json")

    paths = [os.path.join(DOGFOOD_DIR, name) for name in CURATED_ARTIFACTS]
    _run([sys.executable, "-m", "simplicio_mapper.cli", "contract", "validate", *paths])
    print("\nexamples/ecosystem-dogfood/ refreshed and contract-valid.")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--check", action="store_true",
        help="verify examples/ecosystem-dogfood/ is present and contract-valid, without regenerating",
    )
    args = parser.parse_args(argv)
    if args.check:
        return check(args)
    return regenerate(args)


if __name__ == "__main__":
    raise SystemExit(main())
