"""Project mapper that emits the Simplicio machine-readable artifacts.

This is the Python port of ``bin/mapper-artifacts.js``. It produces
``.simplicio/project-map.json`` (schema ``simplicio.project-map/v1``) and
``.simplicio/precedent-index.json`` (schema ``simplicio.precedent-index/v1``)
as documented in ``SIMPLICIO_INTEGRATION.md``.

Split (issue #159) from a single ~1830-line ``mapper.py`` into this package:

- ``.parse`` -- discovery/read layer (filesystem walk, text/import/symbol
  regex parsing, per-file role/importance tagging, precedent extraction).
- ``.graph`` -- call-graph, symbol-index, architecture-inventory and
  macro-map construction (cross-file structure over the discovered files).
- ``.emit`` -- serialization: assembles and writes ``.simplicio/*.json``
  artifacts plus the rendered markdown/SVG architecture docs.

Pure move-and-wire refactor: no renamed public API, no behavior change.
Every name importable from the old ``simplicio_mapper.mapper`` module
(including internal-looking ``_prefixed`` helpers that other modules in
this package import directly, e.g. ``_now_iso``, ``_slugify``) is
re-exported here at the exact same dotted path so external imports never
notice the split.
"""

from __future__ import annotations

from .emit import (
    _build_agent_tree,
    _call_graph_file_graph,
    _file_ref,
    _global_diagram_svgs,
    _layer_module_graph,
    _module_dependency_graph,
    _render_architecture_overview,
    _render_call_graph_doc,
    _render_layers_doc,
    _render_module_doc,
    _slugify,
    _write_json_stable,
    _write_text_stable,
    build_artifacts,
    export_architecture_docs,
    write_architecture_docs,
    write_mapping_artifacts,
)
from .graph import (
    _ARCH_CHECKS,
    _CALL_GRAPH_LANGUAGES,
    _CALL_SKIP_NAMES,
    _ENDPOINT_EXTS,
    _build_architecture_inventory,
    _build_call_graph,
    _build_symbol_index,
    _call_expressions,
    _candidate_import_targets,
    _collect_architecture_signals,
    _is_macro_screen,
    _line_number,
    _macro_git,
    _macro_layers_for_path,
    _macro_roles_for_path,
    _nearest_symbol,
    _strip_known_ext,
    _symbol_definitions_for_file,
    build_macro_map,
)
from .parse import (
    _JSON_WRITE_OPTIONS,
    _NATIVE_IMPORT_LANGUAGES,
    _PRECEDENT_PATTERNS,
    _RE_CAMEL,
    _RE_CONFIG,
    _RE_DOMAIN,
    _RE_NON_ALNUM,
    _RE_PLACEHOLDER,
    _RE_ROUTE,
    _RE_TEST_FILE,
    _RE_TEST_PATH,
    _RE_UI,
    _SYMBOL_PATTERNS,
    ARCHITECTURE_INVENTORY_SCHEMA,
    ARTIFACT_SCHEMA,
    ARTIFACT_VERSION,
    CALL_GRAPH_SCHEMA,
    CONFIG_FILES,
    ENTRYPOINT_STEMS,
    LANGUAGE_BY_EXT,
    LLM_DIRECTIVES,
    MACRO_MAP_SCHEMA,
    PRECEDENT_SCHEMA,
    SKIP_DIRS,
    SYMBOL_INDEX_SCHEMA,
    TEXT_EXTS,
    TOKEN_STOPWORDS,
    _agent_id_from_seed,
    _brown_hilbert_address,
    _build_brown_hilbert_map,
    _build_file_inventory,
    _build_precedent_items,
    _cached_parse_file,
    _collect_entities,
    _collect_text_files,
    _detect_changed_files,
    _extract_snippet,
    _git_status_map,
    _group_modules,
    _importance_for,
    _iso,
    _json_text,
    _language_for,
    _layers_for_file,
    _load_previous_map,
    _module_name_for_path,
    _normalize_rel,
    _now_iso,
    _parse_imports,
    _parse_json_safe,
    _parse_symbols,
    _read_safe,
    _responsibility_for_file,
    _roles_for,
    _sha256,
    _should_skip_dir,
    _token_words,
    _walk,
)

__all__ = [
    "ARCHITECTURE_INVENTORY_SCHEMA",
    "ARTIFACT_SCHEMA",
    "ARTIFACT_VERSION",
    "CALL_GRAPH_SCHEMA",
    "CONFIG_FILES",
    "ENTRYPOINT_STEMS",
    "LANGUAGE_BY_EXT",
    "LLM_DIRECTIVES",
    "MACRO_MAP_SCHEMA",
    "PRECEDENT_SCHEMA",
    "SKIP_DIRS",
    "SYMBOL_INDEX_SCHEMA",
    "TEXT_EXTS",
    "TOKEN_STOPWORDS",
    "_ARCH_CHECKS",
    "_CALL_GRAPH_LANGUAGES",
    "_CALL_SKIP_NAMES",
    "_ENDPOINT_EXTS",
    "_JSON_WRITE_OPTIONS",
    "_NATIVE_IMPORT_LANGUAGES",
    "_PRECEDENT_PATTERNS",
    "_RE_CAMEL",
    "_RE_CONFIG",
    "_RE_DOMAIN",
    "_RE_NON_ALNUM",
    "_RE_PLACEHOLDER",
    "_RE_ROUTE",
    "_RE_TEST_FILE",
    "_RE_TEST_PATH",
    "_RE_UI",
    "_SYMBOL_PATTERNS",
    "_agent_id_from_seed",
    "_brown_hilbert_address",
    "_build_agent_tree",
    "_build_architecture_inventory",
    "_build_brown_hilbert_map",
    "_build_call_graph",
    "_build_file_inventory",
    "_build_precedent_items",
    "_build_symbol_index",
    "_cached_parse_file",
    "_call_expressions",
    "_call_graph_file_graph",
    "_candidate_import_targets",
    "_collect_architecture_signals",
    "_collect_entities",
    "_collect_text_files",
    "_detect_changed_files",
    "_extract_snippet",
    "_file_ref",
    "_git_status_map",
    "_global_diagram_svgs",
    "_group_modules",
    "_importance_for",
    "_is_macro_screen",
    "_iso",
    "_json_text",
    "_language_for",
    "_layer_module_graph",
    "_layers_for_file",
    "_line_number",
    "_load_previous_map",
    "_macro_git",
    "_macro_layers_for_path",
    "_macro_roles_for_path",
    "_module_dependency_graph",
    "_module_name_for_path",
    "_nearest_symbol",
    "_normalize_rel",
    "_now_iso",
    "_parse_imports",
    "_parse_json_safe",
    "_parse_symbols",
    "_read_safe",
    "_render_architecture_overview",
    "_render_call_graph_doc",
    "_render_layers_doc",
    "_render_module_doc",
    "_responsibility_for_file",
    "_roles_for",
    "_sha256",
    "_should_skip_dir",
    "_slugify",
    "_strip_known_ext",
    "_symbol_definitions_for_file",
    "_token_words",
    "_walk",
    "_write_json_stable",
    "_write_text_stable",
    "build_artifacts",
    "build_macro_map",
    "export_architecture_docs",
    "write_architecture_docs",
    "write_mapping_artifacts",
]
